#!/bin/bash
### BY VINISSH ###
rm -f ackinstall
rm -f Plus
rm -f ackinstall*
rm -f Plus*
clear
echo ""
echo -e "\033[1;33mATUALIZANDO PACOTES \033[1;32m( APT UPDATE & APT UPGRADE )"
echo ""
echo -e "\033[1;33mUM MOMENTO..."
apt-get update -y  > /dev/null 2>&1 && apt-get upgrade -y  > /dev/null 2>&1 && apt-get install ufw -y > /dev/null 2>&1
echo ""
echo -e "\033[1;33mPACOTES, ATUALIZADO !"
sleep 3s
echo ""
echo -e "\033[1;33mBAIXANDO, INSTALADOR \033[1;32m( PLUS/MOD )"
sleep 3s
wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/Plus > /dev/null 2>&1
echo ""
echo -e "\033[1;33mBAIXADO !"
sleep 3s
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[1;32m( PLUS/MOD )"
sleep 5s
chmod +x Plus; ./Plus
rm -f Plus*
cd /bin/ && rm -f menu*
clear
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[1;32m( ACKINSTALL )"
sleep 5s
 ### "APT INSTALL"
echo ""
echo -e "\033[1;33mBAIXANDO, PACOTES EXTRAS \033[1;32m( HTOP + GLANCES + ETC )"
sleep 3s
apt-get install screen -y > /dev/null 2>&1
apt-get install htop -y > /dev/null 2>&1
apt-get install iptables -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install slurm -y > /dev/null 2>&1
apt-get install intel-microcode -y > /dev/null 2>&1
apt-get install haveged -y > /dev/null 2>&1
apt-get install ethtool -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install python3.7 -y > /dev/null 2>&1
apt-get install gcc -y > /dev/null 2>&1
apt-get install build-essential -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install speedtest-cli -y > /dev/null 2>&1
apt-get install nethogs -y > /dev/null 2>&1
apt-get remove apache -y > /dev/null 2>&1
apt-get remove rpcbind -y > /dev/null 2>&1
apt-get remove unscd -y > /dev/null 2>&1
apt-get autoremove -y > /dev/null 2>&1
pip install glances > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
### "HORARIO DE SAO PAULO" ###
echo ""
echo -e "\033[1;33mDEFININDO, HORARIO DO SISTEMA \033[1;32m( SÃO PAULO )"
sleep 3s
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
### "SWAPPING" ###
echo ""
echo -e "\033[1;33mCRIANDO MEMORIA SWAP \033[1;32m( 1 GB )"
sleep 3s
fallocate -l 1G /swapfile > /dev/null 2>&1
chmod 600 /swapfile
mkswap /swapfile > /dev/null 2>&1
swapon /swapfile > /dev/null 2>&1
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
echo ""
echo -e "\033[1;33mCONFIGURANDO HAVEGED \033[1;32m( ENTROPIA DO KERNEL ) "
sleep 3s
### "HAVEGED" ###
echo -n > /etc/default/haveged
echo "DAEMON_ARGS="-w 16384"" >> /etc/default/haveged
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "AUTO MENU " ###
echo ""
echo -e "\033[1;33mHABILITANDO O COMANDO AUTO \033[1;32m( MENU )"
sleep 3s
grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
echo "menu;" >> /etc/profile
echo "export TMOUT=0" >> /etc/profile
#'+++++++++++++++++++++++++++++++++++++++++++'
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "FERRAMENTAS" ###
echo ""
echo -e "\033[1;33mBAIXANDO FERRAMENTAS \033[1;32m ( TUNING + SWAP MEMORY ETC ) "
sleep 3s
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f blockt*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f tuning*
cd /bin/ && rm -f atualizar*
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/blocksite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/blockt > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/tuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/atualizar > /dev/null 2>&1
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x blockt
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x tuning
cd /bin/ && chmod +x atualizar
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
echo ""
echo -e "\033[1;33mBAIXANDO PYTHON SOCKS \033[1;32m( WSOCKS + OPEN.PY )"
sleep 3s
### "PYTHON SOCKS" ###
cd /etc/SSHPlus && rm -rf proxy.py*
cd /etc/SSHPlus && rm -rf open.py*
cd /etc/SSHPlus && rm -rf wsproxy.py*
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/PYTHON%20SOCKS/proxy.py > /dev/null 2>&1
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/PYTHON%20SOCKS/open.py > /dev/null 2>&1
cd /etc/SSHPlus && chmod +x proxy.py
cd /etc/SSHPlus && chmod +x open.py
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "BADVPN UDP" ###
echo ""
echo -e "\033[1;33mBAIXANDO BADVPN-UDP \033[1;32m( BADVPN + BADVPN-UDPGW )"
sleep 3s
cd /bin/ && rm -f badvpn*
cd /bin/ && rm -f badvpn-udpgw*
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/BADVPN%20UDP/badvpn > /dev/null 2>&1
cd /bin/ && wget https://github.com/vinissh/ACKHTTP-SERVER-MANAGER/raw/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/BADVPN%20UDP/badvpn-udpgw > /dev/null 2>&1
cd /bin/ && chmod +x badvpn
cd /bin/ && chmod +x badvpn-udpgw
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "BOTSSH" ###
echo ""
echo -e "\033[1;33mBAIXANDO BOTSSH \033[1;32m( BOT TELEGRAM )"
sleep 3s
cd /bin/ && rm -f botssh
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/BOTSSH/botssh > /dev/null 2>&1
cd /bin/ && chmod +x botssh
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "SLOW-DNS" ###
echo ""
echo -e "\033[1;33mBAIXANDO SLOW DNS \033[1;32m( SLOWDNS MANAGER )"
sleep 3s
rm -rf /etc/slowdns*
mkdir /etc/slowdns
rm -f /bin/slowdns*
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns > /dev/null 2>&1
cd /etc/slowdns && wget https://github.com/vinissh/ACKHTTP-SERVER-MANAGER/raw/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/dns-server > /dev/null  2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/remove-slow > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/restartdns > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns-drop > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns-info > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns-socks > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns-ssh > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/slowdns-ssl > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/startdns > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/SLOWDNS/stopdns > /dev/null 2>&1
cd /bin/ && chmod +x slowdns
cd /etc/slowdns && chmod +x dns-server
cd /etc/slowdns && chmod +x remove-slow
cd /etc/slowdns && chmod +x restartdns
cd /etc/slowdns && chmod +x slowdns-drop
cd /etc/slowdns && chmod +x slowdns-info
cd /etc/slowdns && chmod +x slowdns-socks
cd /etc/slowdns && chmod +x slowdns-ssh
cd /etc/slowdns && chmod +x slowdns-ssl
cd /etc/slowdns && chmod +x startdns
cd /etc/slowdns && chmod +x stopdns
#'+++++++++++++++++++++++++++++++++++++++++++'#
# ACKHTTP SERVER +++++ ACKHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "MENU, CONEXAO, ETC" ###
echo ""
echo -e "\033[1;33mBAIXANDO LISTA \033[1;32m(MENU + CONEXAO + ETC)"
sleep 3s
cd /bin/ && rm -f conexao*
cd /bin/ && rm -f menu*
cd /bin/ && rm -f sshmonitor*
cd /bin/ && rm -f criarusuario*
cd /bin/ && rm -f uexpired*
cd /bin/ && rm -f remover*
cd /bin/ && rm -f criarteste*
cd /bin/ && rm -f alterarlimite*
cd /bin/ && rm -f alterarsenha*
cd /bin/ && rm -f detalhes*
cd /bin/ && rm -f infousers*
cd /bin/ && rm -f expcleaner*
cd /bin/ && rm -f banner*
cd /bin/ && rm -f mudardata*
cd /bin/ && rm -f delscript*
cd /bin/ && rm -f senharoot*
cd /bin/ && rm -f ovpn18*
cd /bin/ && rm -f v2raymanager*
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/conexao > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/sshmonitor > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/criarusuario > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/uexpired > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/remover > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/criarteste > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/alterarlimite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/alterarsenha > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/detalhes > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/infousers > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/expcleaner > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/banner > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/mudardata > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/delscript > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/senharoot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/ovpn18 > /dev/null 2>&1
cd /bin/ && wget https://github.com/vinissh/ACKHTTP-SERVER-MANAGER/raw/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/MENU%2C%20CONEX%C3%83O%2C%20ETC/v2raymanager > /dev/null 2>&1
cd /bin/ && chmod +x conexao
cd /bin/ && chmod +x menu
cd /bin/ && chmod +x sshmonitor
cd /bin/ && chmod +x criarusuario
cd /bin/ && chmod +x uexpired
cd /bin/ && chmod +x remover
cd /bin/ && chmod +x criarteste
cd /bin/ && chmod +x alterarlimite
cd /bin/ && chmod +x alterarsenha
cd /bin/ && chmod +x detalhes
cd /bin/ && chmod +x infousers
cd /bin/ && chmod +x expcleaner
cd /bin/ && chmod +x banner
cd /bin/ && chmod +x mudardata
cd /bin/ && chmod +x delscript
cd /bin/ && chmod +x senharoot
cd /bin/ && chmod +x ovpn18
cd /bin/ && chmod +x v2raymanager
#######################################
#### "FIM" ####
clear
echo -e "\033[01;31m===================================================================="
echo -e " \033[1;32m[ INSTALAÇÃO CONCLUIDA! ] \033[1;33m"
echo -e "\033[01;31m===================================================================="
echo -e "\033[1;33mREPOSITORIO, OFICIAL NO GITHUB"
echo -e "\033[1;32mhttps://github.com/vinissh/ACKHTTP-SERVER-MANAGER "
echo -e "\033[01;31m===================================================================="
echo -e "|       \033[01;32mVPS SERVER\033[01;31m      ______         \033[01;32mCR34T3D  BY:\033[01;31m                |"
echo "|                    .-.      .-.                                  |"
echo "|                   /            \                                 |"
echo -e "|                  | [\033[01;32m VINISSH\033[01;31m] |                                |"
echo "|                  |,  .-.  .-.  ,|                                |"
echo "|                  | )(|_/  \|_)( |                                |"
echo "|                  |/     /\     \|                                |"
echo "|          _       (_     ^^     _)                                |"
echo "|  _\ ____) \_______\__|IIIIII|__/_______________________________  |"
echo "| (_)[___]{}<________|-\IIIIII/-|________________________________/ |"
echo "|   /     )_/        \          /                                  |"
echo "|                     \ ______ /                                   |"
echo -e "\033[01;31m===================================================================="
echo -e "\033[1;33m PARA INICIAR O SCRIPT, DIGITE ( menu ) \033[0m"
echo ""
echo -e "\033[1;33m SCRIPT DESENVOLVIDO POR:\033[0m"
echo -e "\033[1;32m@VINISSH"
echo ""
echo -e "\033[1;33m PARA RELATAR BUGS, OU DÚVIDAS, CONTATE-ME ! 
( TELEGRAM ) \033[0m"
echo -e "\033[1;32m@VINISSH"
echo -e "\033[01;31m====================================================================\033[1;37m"
echo ""
echo "" 
