#!/bin/bash
### "BY GOD OF SKY " ###
#ESSE SCRIPT AUTO INICIAR COM O SERVIDOR !"
#MELHORIAS NA REDE TCP DO SISTEMA!"
mount -o remount,noatime,nodiratime,nobarrier auto /
mount -o remount,noatime,nodiratime, auto /dev
mount -o remount,noatime,nodiratime, auto /proc
mount -o remount,noatime,nodiratime, auto /sys
### INIT ROUTE
/sbin/ip route | while read p; do ip route change $p initcwnd 10 initrwnd 10 cwnd 10 mtu lock 9000 congctl lock illinois quickack 1; done
/sbin/ifconfig eth0 mtu 9000
/sbin/ifconfig eth0 txqueuelen 13888
/sbin/ifconfig lo mtu 9000
/sbin/ifconfig lo txqueuelen 13888
ethtool -G eth0 rx 3502
ethtool -G eth0 tx 2048
bash -c 'echo 1 > /sys/module/processor/parameters/ignore_ppc'
bash -c 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'
bash -c 'echo 4400000 > /scaling_max_freq'
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo "obase=16;2^$(nproc)-1" | bc > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo 16384 > /sys/module/nf_conntrack/parameters/hashsize
echo 16384 > /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
