#!/bin/bash
clear
rm -f multiportas*
apt install python3.7 -y > /dev/null 2>&1
echo -e "\033[1;33m SCRIPT APENAS PARA USUARIOS \033[1;32m(SSHPLUS)\033[1;32m"
sleep 6s
echo ""
echo -e "\033[1;33mREMOVENDO \033[1;31mWSPROXY.PY \033[1;37m+ \033[1;31mPROXY.PY \033[1;37m+ \033[1;31mBADVPN-UDP"
sleep 3s
cd /etc/SSHPlus && rm -rf wsproxy.py*
cd /etc/SSHPlus && rm -rf proxy.py*
echo  ""
echo -e "\033[1;33mINSTALANDO PROXY.PY \033[1;32m(MODO WEBSOCKET - ABRIR PORTAS)"
sleep 3s
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/PYTHON%20SOCKS/proxy.py > /dev/null 2>&1
cd /etc/SSHPlus && chmod +x proxy.py
echo  ""
echo -e "\033[1;33mINSTALANDO BADVPN-UDP \033[1;32m(MODO ABRIR PORTAS)"
sleep 3s
cd /bin/ && rm -f badvpn*
cd /bin/ && rm -f badvpn-udpgw*
cd /bin/ && wget https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/BADVPN%20UDP/badvpn > /dev/null 2>&1
cd /bin/ && wget https://github.com/vinissh/ACKHTTP-SERVER-MANAGER/raw/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/BADVPN%20UDP/badvpn-udpgw > /dev/null 2>&1
cd /bin/ && chmod +x badvpn
cd /bin/ && chmod +x badvpn-udpgw
echo ""
sleep 5s
clear
echo -e "\033[1;33mMODIFACOES FINALIZADAS !\033[1;32m"
sleep 3s
echo ""
echo -e "\033[1;36m QUANDO ABRIR O MODO DE CONEXAO >>> ( PROXY SOCKS )\033[1;32m"
echo -e "\033[1;36m SELECIONE A OPCAO (SOCKS SSH) PARA UTILIZAR.\033[1;32m"
echo ""
echo -e "\033[1;36m PARA VOLTAR, DIGITE ( menu )\033[1;37m"
echo "" 
sleep 3s
echo ""
echo ""
