#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;36m/"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;32m \033[1;32m--------------   \033[1;37mACKHTTP SERVER MANAGER V 1.2   \033[1;32m--------------\033[1;32m"
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mREPOSITORIO, OFICIAL NO GITHUB"
echo -e "\033[1;32mhttps://github.com/vinissh/ACKHTTP-SERVER-MANAGER "
echo -e "\033[01;34m===================================================================="
echo ""
echo -e "\033[1;33mO SCRIPT \033[1;32m(ACKHTTP SERVER MANAGER) \033[1;33mUSAR REPOSITORIOS \033[1;32m(SSHPLUS)"
echo -e "\033[1;33mSENDO ASSIM, ESSE SCRIPT É UMA VERSÃO ALTERNATIVA"
echo -e "\033[1;33mCOM RECURSOS EXCLUSIVOS E APRIMORADOS."
echo ""
echo -e "\033[01;34m===================================================================="
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;37mCONTINUAR, INSTALADOR ??? [sim/não]: \033[1;37m"; read x
[[ $x = @(nao|NAO) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mCONFIRMANDO CHAVE... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/vinissh/ACKHTTP-SERVER-MANAGER/main/SCRIPT%20ACKHTTP%20SERVER/SCRIPT%20ACKHTTP%20SERVER/FERRAMENTAS/list > /dev/null 2>&1; verif_key
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
sleep 3s
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mINICIANDO INSTALAÇÃO...\033[1;32m"
sleep 3s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
echo -e "\033[1;37m $system                          $date"
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;32m \033[1;32m--------------   \033[1;37mACKHTTP SERVER MANAGER V.1.1.A   \033[1;32m--------------\033[1;32m"
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mANTES DE CONTINUAR..."
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
echo ""
echo -e "\033[1;33m- LOGIN"
echo -e "\033[1;33m- SENHAS"
echo -e "\033[1;33m- LIMITE"
echo -e "\033[1;33m- DIAS"
echo -e ""
echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;34m[\033[1;37m1 •\033[1;34m] \033[1;37m---  MANTER, TODOS OS DADOS \033[0m"
echo ""
echo -e "\033[1;34m[\033[1;37m2 •\033[1;34m] \033[1;37m---  EXCLUIR, DADOS DISPONIVEIS \033[0m"
echo -e "\033[01;34m===================================================================="
echo ""
tput setaf 7 ; tput bold ; read -p "[ESCOLHA UM NUMERO] ----- " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
fun_attlist () {
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
echo ""
cd $HOME
echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenu\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
clear
